# Generated by Django 3.2.7 on 2021-11-04 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='show',
            name='provider',
        ),
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.network'),
        ),
        migrations.AlterField(
            model_name='show',
            name='show',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.AddField(
            model_name='show',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.user'),
        ),
    ]
