# Generated by Django 3.2.7 on 2021-11-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211104_1900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Provider',
        ),
    ]
