# Generated by Django 3.2.7 on 2021-11-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_user_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='user',
            new_name='provider',
        ),
    ]
