# Generated by Django 3.2.7 on 2021-11-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_show_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='password1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='password2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
